name: "1.21 Gigawatts"
description: "Injects into Flux Capacitor"
inputs:
    endpoint:
        description: "Flux Capacitor API endpoint"
        required: true
    token:
        description: "Flux Capacitor API token"
        required: true
    file:
        description: "Location of the Fluxfile to inject"
        required: true
        default: "./Fluxfile"
    timeout:
        description:
            "How long before the deployment is considered as failed (seconds)"
        required: true
        default: "1800"
    branch:
        description: "Branch to deploy"
        required: false
        default: ""
runs:
    using: "node16"
    main: "dist/index.js"
